-------------------------------------------------------------------------------
Test set: com.cloudwebshop.remotetests.UserServiceRemoteTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 9.517 s <<< FAILURE! -- in com.cloudwebshop.remotetests.UserServiceRemoteTest
com.cloudwebshop.remotetests.UserServiceRemoteTest.testCreateOrderForUser -- Time elapsed: 0.296 s <<< ERROR!
org.springframework.web.client.HttpServerErrorException$InternalServerError: 500 : "{"errorId":"89ad416f-d254-4309-8cef-592a5b28a2f9","timestamp":"2025-08-28T10:45:55.530952767","status":500,"error":"Internal Server Error","message":"An unexpected error occurred. Please report this with error ID: 89ad416f-d254-4309-8cef-592a5b28a2f9","path":"uri=/api/v1/users"}"
	at org.springframework.web.client.HttpServerErrorException.create(HttpServerErrorException.java:102)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:186)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:137)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:942)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:891)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:790)
	at org.springframework.web.client.RestTemplate.postForEntity(RestTemplate.java:538)
	at com.cloudwebshop.remotetests.UserServiceRemoteTest.testCreateOrderForUser(UserServiceRemoteTest.java:51)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
